// <auto-generated />
namespace RSHCEnteties.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _05092023AddedIdentityRoles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_05092023AddedIdentityRoles));
        
        string IMigrationMetadata.Id
        {
            get { return "202309052041357_05-09-2023-AddedIdentityRoles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
