// <auto-generated />
namespace RSHCEnteties.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RSHCPathtoimageadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RSHCPathtoimageadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202309142123124_RSHC Path to image added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
