// <auto-generated />
namespace RSHCEnteties.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _22092023AddedDeviceName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_22092023AddedDeviceName));
        
        string IMigrationMetadata.Id
        {
            get { return "202309221937118_22-09-2023 Added Device Name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
