// <auto-generated />
namespace RSHCEnteties.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _28092023DBInitBasicModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_28092023DBInitBasicModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202309282320203_28-09-2023 DB Init Basic Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
